###
### Simpliest script for keys rotation 
###
name: 'Rotate Production AWS key'


on:
  schedule:
    - cron: '0 0 1 * *' 

jobs:
  rotate:
    name: rotate iam user keys for Production
    runs-on: ubuntu-latest
    steps:
      - name: rotate Production aws keys
        uses: seekingalpha/github-action-rotate-aws-secrets@v1.0.5
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PRODUCTION_DEPLOY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRODUCTION_DEPLOY_KEY }}
          GITHUB_ACCESS_KEY_NAME: 'AWS_PRODUCTION_DEPLOY_ID'
          GITHUB_SECRET_KEY_NAME: 'AWS_PRODUCTION_DEPLOY_KEY'
          IAM_USERNAME: ${{ secrets.AWS_IAM_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.SAMW_GITHUB_TOKEN }}
          OWNER_REPOSITORY: ${{ github.repository }}
