name: 'Rotate  AWS key'


on:
  schedule:
    - cron: '0 0 1 * *' 

jobs:
  rotate:
    name: rotate iam user keys 
    runs-on: ubuntu-latest
    steps:
      - name: rotate  aws keys
        uses: seekingalpha/github-action-rotate-aws-secrets@v1.0.5
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_USER_GITHUB_ROCKETCHAT_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_USER_GITHUB_ROCKETCHAT_SECRET_ACCESS_KEY }}
          GITHUB_ACCESS_KEY_NAME: 'AWS_USER_GITHUB_ROCKETCHAT_ACCESS_KEY_ID'
          GITHUB_SECRET_KEY_NAME: 'AWS_USER_GITHUB_ROCKETCHAT_SECRET_ACCESS_KEY'
          IAM_USERNAME: ${{ secrets.AWS_IAM_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.ROCKETCHAT_GITHUB_TOKEN }}
          OWNER_REPOSITORY: ${{ github.repository }}
