name: Rotate AWS secrets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # monthly


jobs:
  rotate-aws-secrets:
    name: Rotate AWS secrets
    runs-on: ubuntu-latest
    steps:
      - name: Rotate AWS secrets
        uses: kneemaa/github-action-rotate-aws-secrets@v1.1.0
        env:
          OWNER_REPOSITORY: ${{ github.repository }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.ROCKETCHAT_GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID:      ${{ secrets.AWS_USER_GITHUB_ROCKETCHAT_ACCESS_KEY_ID }}
          GITHUB_ACCESS_KEY_NAME:             AWS_USER_GITHUB_ROCKETCHAT_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_USER_GITHUB_ROCKETCHAT_SECRET_ACCESS_KEY }}
          GITHUB_SECRET_KEY_NAME:             AWS_USER_GITHUB_ROCKETCHAT_SECRET_ACCESS_KEY
